#!/usr/bin/env python3

import numpy as np
import xarray as xr
import pandas as pd
import argparse

parser = argparse.ArgumentParser()
parser.add_argument(
    '--csv',
    help='The `csv` file containing the library constructs.',
    required=True,
)
parser.add_argument(
    '--reads',
    help='The `nc` file containing the library construct read counts.',
    required=True,
)
parser.add_argument(
    '--output',
    help='The output prefix.',
    default="library",
)


def _save_library(library, out_csv_file, out_fasta_file, out_txt_file) -> None:

    library.to_csv(out_csv_file, index=False)

    # Get the FASTA headers

    headers = (
        library["name"] +
        " (" +
        library["sublibrary"]
        + ")"
    ).values

    # Get the sequences

    sequences = (
        library["five_const"] +
        library["five_padding"] +
        library["design"] +
        library["three_padding"] +
        library["barcode"] +
        library["three_const"]
    ).values

    # Save to FASTA

    with open(out_fasta_file, "w") as f:
        for i in range(len(sequences)):
            f.write(">" + headers[i] + "\n")
            f.write(sequences[i] + "\n")

    # Save to txt

    with open(out_txt_file, "w") as f:
        for i in range(len(sequences)):
            f.write(sequences[i] + "\n")


#
# Input and output files
#

args = parser.parse_args()

out_csv_file = f"{args.output}.csv"
out_fasta_file = f"{args.output}.fasta"
out_txt_file = f"{args.output}.txt"

#
# Loading
#

library = pd.read_csv(args.csv, keep_default_na=False)

# Get the predicted reads for the library constructs
# We take the mean of the 2A3 and DMS reads

n = len(library)
library_reads = np.zeros(n, dtype=float)
library_reads_arr = xr.load_dataset(args.reads)['reads'].values.mean(1)

m = library_reads_arr.shape[0]
library_reads[:m] = library_reads_arr
library['reads'] = library_reads_arr

#
# Sorting
#

ix = np.argsort(library_reads)
library['index'] = ix
library = library.iloc[ix]

#
# Saving
#

_save_library(library, out_csv_file, out_fasta_file, out_txt_file)
